<h3>HomeWork 3 </h3>

<h3>Name : Hassan Magdy Abdallah Nassar</h3>
<h3>Group: 4</h3>

In [1]:
import numpy as np

<h3> Question 1 </h3>

<strong><p> First I tried to write Matrix A of probabilities.
<li>Then i used in Matrix B index 0 as position 10
<li> at Last i put position 10 in the order in Matrix C </p></strong>

In [2]:
            #   10,   1,   2,   3,   4,   5,   6 ,  7,   8,   9                     
A = np.array([[.25,   0,   0,   0,   0,   0,  .2,   0,   0,  .2], #10
              [ 0 ,   0,  .2,  .2,   0,   0,   0,   0,   0,   0], #1
              [ 0 , .25,   0,  .2,  .2, 1/6,   0,   0,   0,   0], #2
              [ 0 , .25,  .2,   0,   0, 1/6,  .2,   0,   0,   0], #3
              [ 0 ,   0,  .2,   0,   0, 1/6,   0, .25,  .2,   0], #4
              [ 0 ,   0,  .2,  .2,  .2,   0,  .2, .25,  .2,  .2], #5
              [.25,   0,   0,  .2,   0, 1/6,   0,   0,   0,  .2], #6
              [ 0 ,   0,   0,   0,  .2,   0,   0, .25,  .2,   0], #7
              [ 0 ,   0,   0,   0,  .2, 1/6,   0,   0,  .2,  .2], #8
              [.25,   0,   0,   0,   0, 1/6,  .2,   0,  .2,  .2]])#9

            #   10,   1,   2,   3,   4,   5,   6 ,  7,   8,   9                     
B = np.array([[  4,  0,   0,    0,   0,   0,  -1,   0,   0,  -1], #10
              [  0,  4,  -1,   -1,   0,   0,   0,   0,   0,   0], #1
              [  0, -1,   5,   -1,  -1,  -1,   0,   0,   0,   0], #2
              [  0, -1,  -1,    5,   0,  -1,  -1,   0,   0,   0], #3
              [  0,  0,  -1,   -1,   5,  -1,   0,  -1,  -1,   0], #4
              [  0,  0,  -1,   -1,  -1,   6,  -1,   0,  -1,  -1], #5
              [ -1,  0,   0,    0,   0,  -1,   5,   0,   0,  -1], #6
              [  0,  0,   0,    0,  -1,   0,   0,   4,  -1,   0], #7
              [  0,  0,   0,    0,  -1,  -1,   0,  -1,   5,  -1], #8
              [ -1,  0,   0,    0,   0,  -1,  -1,   0,  -1,   5]])#9
            #     1,   2,    3,   4,   5,   6,   7,   8,   9,  10                  
C = np.array([[   4,  -1,   -1,   0,   0,   0,   0,   0,   0,  0 ],   #1
              [  -1,   5,   -1,  -1,  -1,   0,   0,   0,   0,  0 ],   #2
              [  -1,  -1,    5,   0,  -1,  -1,   0,   0,   0,  0 ],   #3
              [   0,  -1,   -1,   5,  -1,   0,  -1,  -1,   0,  0 ],   #4
              [   0,  -1,   -1,  -1,   6,  -1,   0,  -1,  -1,  0 ],   #5
              [   0,   0,    0,   0,  -1,   5,   0,   0,  -1, -1 ],   #6
              [   0,   0,    0,  -1,   0,   0,   4,  -1,   0,  0 ],   #7
              [   0,   0,    0,  -1,  -1,   0,  -1,   5,  -1,  0 ],   #8
              [   0,   0,    0,   0,  -1,  -1,   0,  -1,   5, -1 ],   #9
              [   0,   0,    0,   0,   0,  -1,   0,   0,  -1,  4 ] ]) #10
b = np.array([1,0,0,0,0,0,0,1,1,1]).reshape(-1,)

In [3]:
from numpy.linalg import inv, solve, norm

def jacobi(A, b, tolerance):
    xk_1 = np.zeros_like(b)
    D = np.diag(A)
    LplusU = A - np.diag(D)
    
    x_k = (b - (LplusU @ xk_1)) / D
    while (norm(x_k - xk_1, 2)/norm(x_k, 2)) > tolerance:
        xk_1 = x_k
        x_k = (b - (LplusU @ xk_1)) / D
    
    return x_k

print(jacobi(B, b, 1e-8))

[0.44264229 0.09019607 0.18710577 0.17367852 0.33832094 0.33333332
 0.25775746 0.46716161 0.53032551 0.51281172]


In [4]:
b1 = np.array([0,0,0,0,0,0,1,1,1,1]).reshape(-1,)
print(jacobi(C, b1, 1e-8))

[0.09019607 0.18710577 0.17367852 0.33832094 0.33333332 0.25775746
 0.46716161 0.53032551 0.51281172 0.44264229]


In [5]:
def siedel(A, b, N):
    x = np.zeros_like(b) # initial solution (zeros)
    LD = np.tril(A)
    U = A - LD
    
    LDinv = inv(LD)
    for i in range(N):
        x = LDinv @ (b - U@x)
    return x

siedel(B, b, 10)

array([0.44108443, 0.0868636 , 0.18247981, 0.17020923, 0.33370456,
       0.32939652, 0.25599328, 0.46483809, 0.52748493, 0.51079183])

In [6]:
siedel(C, b1, 10)

array([0.08650773, 0.18198563, 0.16983857, 0.3332113 , 0.32897585,
       0.25580474, 0.46458981, 0.52718138, 0.51057598, 0.44159518])

<h3>Question 2</h3>

In [7]:
a1 = np.array([[0,1,2],[.5,0,0],[0,.25,0]])
a2 = np.array([[0,6,8],[.5,0,0],[0,.5,0]])
v0 = np.array([[1],[1],[1]])

In [8]:
def powerMethod(a,v):
    val = 0
    vec = []
    vals = []
    for i in range(50):
        val_copy = val
        ve = np.dot(a,v)
        val = max(ve)
        ve = ve/val
        v = ve
        if str(val) == str(val_copy):
            break
        vec.append(ve)
        vals.append(val)
    return vec,vals

<h3> (1) </h3>

In [9]:
l , o =powerMethod(a1,v0)
print(o[-3])
print(l[-3])

[0.88464622]
[[1.        ]
 [0.56519769]
 [0.15972424]]


In [10]:
l, v = np.linalg.eig(a1)
print(l)
print(v)

print()

print(a1 @ v[:, 0])
print(l[0] * v[:, 0])
print()
x = np.random.rand(3)
for i in range(50):
    x = (a1 @ x) / np.linalg.norm(x,2)

lmbda = ((a1@x) / x)[0]
v = x / lmbda
print(lmbda)
print(v)

[ 0.88464618+0.j        -0.44232309+0.2948714j -0.44232309-0.2948714j]
[[-0.86227396+0.j          0.69332593+0.j          0.69332593-0.j        ]
 [-0.48735527+0.j         -0.54259608-0.36171765j -0.54259608+0.36171765j]
 [-0.13772604+0.j          0.11796101+0.28307982j  0.11796101-0.28307982j]]

[-0.76280736+0.j -0.43113698+0.j -0.12183882+0.j]
[-0.76280736+0.j -0.43113698+0.j -0.12183882+0.j]

0.8846461771138722
[0.86227396 0.48735527 0.13772604]


<h3> (2) </h3>

In [11]:
l , o =powerMethod(a2,v0)
print(o[-3])
print(l[-3])

[2.00000002]
[[1.    ]
 [0.25  ]
 [0.0625]]


In [12]:
l, v = np.linalg.eig(a2)
print(l)
print(v)

print()

print(a2 @ v[:, 0])
print(l[0] * v[:, 0])
print()
x = np.random.rand(3)
for i in range(50):
    x = (a2 @ x) / np.linalg.norm(x,2)

lmbda = ((a2@x) / x)[0]
v = x / lmbda
print(lmbda)
print(v)

[ 2.         -0.99999998 -1.00000002]
[[-0.96836405  0.87287156 -0.87287156]
 [-0.24209101 -0.43643579  0.43643578]
 [-0.06052275  0.2182179  -0.21821788]]

[-1.9367281  -0.48418203 -0.12104551]
[-1.9367281  -0.48418203 -0.12104551]

2.0000000000001887
[0.96836405 0.24209101 0.06052275]
